name = "svelte"
imports = 'import { svelte } from "@sveltejs/vite-plugin-svelte";'
plugins = 'context === "ui" ? [svelte()] : []'
dependencies = ["@sveltejs/vite-plugin-svelte"]

[pm]
install = "pnpm install"
script.dev = "pnpm dev"

[package]
dependencies = [
  svelte,
  svelte-plugin
]
